### PR TITLE
replace kernel32-sys to winapi v0.3

### PR DESCRIPTION
**Pull request by tingfeng-key**
replace kernel32-sys to winapi v0.3

### CODE REVIEW

**Comment by tingfeng-key** [comment]
https://github.com/retep998/winapi-rs/issues/1026

https://github.com/Lonami/grammers/issues/156

**Comment by Lonami** [comment]
Thanks for merging! Do you have plans to create a new release on crates.io?

**Comment by snuk182** [comment]
https://crates.io/crates/locate-locale/0.2.0 done

**Comment by Lonami** [comment]
Thanks a lot :)

**Pull request merged**
